let age;
console.log (typeof age); 
let num = 50;
console.log (typeof num);
let cif = 10203045n;
console.log (typeof cif); 
let str = 'Мама';
console.log (typeof str); 
let TF = true;
console.log (typeof TF); 
let sim = Symbol();
console.log (typeof sim); 
let user = {age:19};
console.log (typeof user); 
let per = null;
console.log (typeof per); 
let us = function(){};
console.log (typeof us); 